"""
Project-type-specific milestone templates.
Each entry: (title, description, target_pct, payment_pct)
target_pct  = completion % at which this milestone is triggered
payment_pct = % of total project budget released at this milestone
"""

MILESTONE_TEMPLATES = {

    'road': [
        (10,  'Site Clearing & Mobilisation',
               'Land clearing, equipment mobilisation, traffic diversion plans in place.',
               10, 8),
        (25,  'Earthworks & Sub-base',
               'Excavation, grading, compaction and sub-base layer laid to specification.',
               25, 15),
        (45,  'Base Course & Drainage',
               'Base course compacted, side drains, culverts and drainage channels installed.',
               45, 20),
        (65,  'Asphalt / Surface Course',
               'Binder and wearing courses laid, road markings begun.',
               65, 22),
        (85,  'Road Furniture & Markings',
               'Road signs, guard rails, road markings, streetlights installed.',
               85, 20),
        (100, 'Final Inspection & Handover',
               'Punch-list cleared, road opened to traffic, as-built drawings submitted.',
               100, 15),
    ],

    'bridge': [
        (15,  'Foundation & Piling',
               'Piles driven/bored, pile caps cast, abutment foundations completed.',
               15, 12),
        (30,  'Abutments & Piers',
               'Abutment walls and bridge piers constructed to bearing level.',
               30, 18),
        (55,  'Deck & Superstructure',
               'Girders erected, deck slab cast, parapet walls started.',
               55, 25),
        (75,  'Parapet, Railings & Approach Roads',
               'Bridge railings, expansion joints, approach road ties completed.',
               75, 20),
        (90,  'Waterproofing & Surfacing',
               'Deck waterproofing, surfacing, drainage channels complete.',
               90, 15),
        (100, 'Load Testing & Handover',
               'Load test passed, punch-list cleared, handover certificate issued.',
               100, 10),
    ],

    'school': [
        (15,  'Foundation & Substructure',
               'Setting out, excavation, column bases, ground beam and DPC cast.',
               15, 12),
        (35,  'Superstructure — Block & Columns',
               'All floors\' columns, beams and block walls completed to roof level.',
               35, 20),
        (55,  'Roofing & Windows',
               'Roof trusses erected, sheets fixed, fascia boards, windows and frames installed.',
               55, 20),
        (70,  'Plastering, Floors & Electrical Rough-in',
               'Internal and external plastering, floor screeds, electrical conduits run.',
               70, 18),
        (88,  'Finishing — Painting, Doors & Fixtures',
               'Painting, door/ceiling installation, sanitary fixtures, power outlets complete.',
               88, 18),
        (100, 'Furniture, Handover & Commissioning',
               'School furniture installed, fire safety checked, handover to Ministry.',
               100, 12),
    ],

    'hospital': [
        (10,  'Site Works & Foundation',
               'Site preparation, piling if required, raft/strip foundation cast.',
               10, 8),
        (25,  'Structural Frame',
               'All columns, beams, slabs for all floors completed and cured.',
               25, 15),
        (45,  'MEP Rough-in — Mechanical, Electrical, Plumbing',
               'All MEP services roughed in: HVAC ducts, plumbing stacks, electrical trunking.',
               45, 20),
        (60,  'Envelope — Cladding, Roofing, Glazing',
               'External walls, roof waterproofing, curtain walling and glazing complete.',
               60, 18),
        (80,  'Internal Fit-out & Medical Gas',
               'Partition walls, ceilings, screed, medical gas pipework, ICU & theatre fit-out.',
               80, 20),
        (93,  'Finishing, Painting & Equipment Install',
               'Painting, doors, sanitary ware, nurse call, CCTV, medical equipment installed.',
               93, 12),
        (100, 'Commissioning, Infection Control & Handover',
               'All systems commissioned, infection control clearance, handover to Ministry of Health.',
               100, 7),
    ],

    'water': [
        (15,  'Intake Structure & Borehole / Dam Works',
               'Water source developed: borehole drilled, intake headworks or small dam constructed.',
               15, 12),
        (35,  'Treatment Plant — Civil Works',
               'Treatment plant structure, filter beds, sedimentation tanks constructed.',
               35, 20),
        (55,  'Treatment Plant — Mechanical & Electrical',
               'Pumps, chemical dosing, electrical panels, SCADA installed and tested.',
               55, 22),
        (70,  'Transmission Main',
               'Primary pipeline from source to distribution reservoir laid and pressure-tested.',
               70, 18),
        (88,  'Distribution Network',
               'Secondary pipe network, valves, fire hydrants, consumer connection points installed.',
               88, 18),
        (100, 'Water Quality Testing & Commissioning',
               'Water quality meets NWRMC standards, system commissioned, community handed over.',
               100, 10),
    ],

    'power': [
        (12,  'Civil Works — Substation & Line Routes',
               'Substation foundation, transmission route clearing, pole foundations cast.',
               12, 10),
        (30,  'Substation Equipment Installation',
               'Transformers, switchgear, bus bars, protection relays installed.',
               30, 20),
        (50,  'Transmission & Distribution Lines',
               'Poles erected, stringing of conductors, cross arms and insulators complete.',
               50, 22),
        (70,  'Consumer Connections & Metering',
               'Last-mile connections, smart meters, service cables to households/businesses.',
               70, 20),
        (88,  'Protection & Control Systems',
               'SCADA integration, protection relay testing, earthing systems verified.',
               88, 18),
        (100, 'Energisation, Load Test & Handover',
               'System energised, load test run, safety audit passed, handover to DISCO.',
               100, 10),
    ],

    'housing': [
        (10,  'Site Preparation & Foundation',
               'Setting out, bulk earthworks, foundation excavation and casting complete.',
               10, 8),
        (28,  'Ground Floor Structure',
               'Ground floor columns, beams, slab and block walls to lintel level.',
               28, 15),
        (48,  'Upper Floors & Roof',
               'Upper-floor structures, roof trusses, roofing sheets and fascia complete.',
               48, 20),
        (65,  'External Works & Plastering',
               'External plastering, compound wall, gate, parking area, drainage channels.',
               65, 18),
        (83,  'Internal Finishing & MEP',
               'Internal plastering, screeds, tiling, painting, electrical fit-out, plumbing.',
               83, 22),
        (100, 'Furniture, Landscaping & Handover',
               'Built-in furniture, landscaping, defects remedied, handover to beneficiaries.',
               100, 17),
    ],

    'other': [
        (20,  'Mobilisation & Preliminary Works',
               'Site established, preliminary works and enabling infrastructure complete.',
               20, 15),
        (45,  'Main Works — Phase 1',
               'First half of the primary scope of works completed and inspected.',
               45, 25),
        (70,  'Main Works — Phase 2',
               'Second half of primary scope completed; services rough-in done.',
               70, 25),
        (90,  'Finishing & Commissioning',
               'Finishes, fixtures, testing and commissioning of all systems complete.',
               90, 25),
        (100, 'Final Inspection & Handover',
               'Punch-list cleared, all documentation submitted, site handed over.',
               100, 10),
    ],
}


def get_milestones_for_type(project_type: str) -> list:
    """Return list of (order, title, description, target_pct, payment_pct) tuples."""
    templates = MILESTONE_TEMPLATES.get(project_type, MILESTONE_TEMPLATES['other'])
    return [
        {
            'order': i + 1,
            'title': t[1],
            'description': t[2],
            'target_percentage': t[0],
            'payment_percentage': t[3],
        }
        for i, t in enumerate(templates)
    ]
