# Generated by Django 6.0.5 on 2026-05-10 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('project_type', models.CharField(choices=[('road', 'Road Construction'), ('bridge', 'Bridge'), ('school', 'School Building'), ('hospital', 'Hospital'), ('water', 'Water Infrastructure'), ('power', 'Power Infrastructure'), ('housing', 'Housing'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('satellite_reference_image', models.ImageField(blank=True, null=True, upload_to='satellite/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='projects.contractor')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_percentage', models.FloatField()),
                ('payment_percentage', models.FloatField()),
                ('achieved', models.BooleanField(default=False)),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
        ),
    ]
