# Generated by Django 6.0.5 on 2026-05-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmilestone',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='projectmilestone',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
