# Generated by Django 6.0.5 on 2026-05-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('previous_hash', models.CharField(max_length=256)),
                ('hash', models.CharField(max_length=256, unique=True)),
                ('nonce', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
