# Generated by Django 6.0.5 on 2026-05-10 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('satellite', 'Satellite Image'), ('camera_gov', 'Government Camera'), ('camera_crowd', 'Crowdsourced Camera'), ('drone', 'Drone Footage'), ('document', 'Document')], max_length=30)),
                ('image', models.ImageField(upload_to='evidence/%Y/%m/')),
                ('uploader_name', models.CharField(blank=True, max_length=100)),
                ('uploader_phone', models.CharField(blank=True, max_length=20)),
                ('gps_lat', models.FloatField(blank=True, null=True)),
                ('gps_lng', models.FloatField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Analysis'), ('analyzed', 'Analyzed'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_detections', models.JSONField(default=list)),
                ('detected_elements', models.JSONField(default=dict)),
                ('completion_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('stage_scores', models.JSONField(default=dict)),
                ('analysis_notes', models.TextField(blank=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('model_version', models.CharField(default='yolov3-construction-mvp', max_length=50)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='monitoring.mediaevidence')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCompletionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateTimeField(auto_now_add=True)),
                ('completion_percentage', models.FloatField()),
                ('evidence_count', models.IntegerField()),
                ('method', models.CharField(default='weighted_average', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('triggered_payment', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
