# Generated by Django 6.0.5 on 2026-05-10 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
        ('projects', '0002_alter_projectmilestone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaevidence',
            name='flag_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mediaevidence',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mediaevidence',
            name='source',
            field=models.CharField(choices=[('satellite', 'Satellite Image'), ('camera_gov', 'Government Camera'), ('camera_crowd', 'Crowdsourced'), ('drone', 'Drone Footage'), ('document', 'Document')], max_length=30),
        ),
        migrations.CreateModel(
            name='SiteCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('snapshot_url', models.URLField(blank=True, help_text='HTTP URL for JPEG snapshot. Leave blank for RTSP.')),
                ('rtsp_url', models.CharField(blank=True, help_text='RTSP stream URL (production use)', max_length=300)),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_capture', models.DateTimeField(blank=True, null=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='projects.project')),
            ],
        ),
    ]
